[2022-07-17 08:32:20,629] [face01lib.Core] [Calc.py] [WARNING] 試用期限を過ぎました
[2022-07-17 08:32:20,630] [face01lib.Core] [Calc.py] [WARNING] 引き続きご利用になる場合は下記までご連絡下さい
[2022-07-17 08:35:22,000] [face01lib.Core] [Calc.py] [WARNING] 試用期限を過ぎました
[2022-07-17 08:35:22,000] [face01lib.Core] [Calc.py] [WARNING] 引き続きご利用になる場合は下記までご連絡下さい
[2022-07-17 08:36:57,986] [face01lib.Core] [Calc.py] [WARNING] 試用期限を過ぎました
[2022-07-17 08:36:57,986] [face01lib.Core] [Calc.py] [WARNING] 引き続きご利用になる場合は下記までご連絡下さい
[2022-07-17 08:40:23,734] [face01lib.Core] [Calc.py] [WARNING] 試用期限を過ぎました
[2022-07-17 08:40:23,734] [face01lib.Core] [Calc.py] [WARNING] 引き続きご利用になる場合は下記までご連絡下さい
[2022-07-17 08:40:23,735] [face01lib.Core] [Calc.py] [WARNING] 東海顔認証　担当：袈裟丸 y.kesamaru@tokai-kaoninsho.com
[2022-07-17 08:40:56,632] [face01lib.Core] [Calc.py] [WARNING] 試用期限を過ぎました
[2022-07-17 08:40:56,632] [face01lib.Core] [Calc.py] [WARNING] 引き続きご利用になる場合は下記までご連絡下さい
[2022-07-17 08:40:56,633] [face01lib.Core] [Calc.py] [WARNING] 東海顔認証　担当：袈裟丸 y.kesamaru@tokai-kaoninsho.com
[2022-07-17 08:41:56,474] [face01lib.Core] [Calc.py] [WARNING] 試用期限を過ぎました
[2022-07-17 08:41:56,474] [face01lib.Core] [Calc.py] [WARNING] 引き続きご利用になる場合は下記までご連絡下さい
[2022-07-17 08:41:56,474] [face01lib.Core] [Calc.py] [WARNING] 東海顔認証 担当: 袈裟丸 y.kesamaru@tokai-kaoninsho.com
[2022-07-17 08:42:09,904] [face01lib.Core] [Calc.py] [WARNING] 試用期限を過ぎました
[2022-07-17 08:42:09,904] [face01lib.Core] [Calc.py] [WARNING] 引き続きご利用になる場合は下記までご連絡下さい
[2022-07-17 08:42:09,905] [face01lib.Core] [Calc.py] [WARNING] 東海顔認証 担当: 袈裟丸 y.kesamaru@tokai-kaoninsho.com
[2022-07-17 08:42:22,403] [face01lib.Core] [Calc.py] [WARNING] 試用期限を過ぎました
[2022-07-17 08:42:22,404] [face01lib.Core] [Calc.py] [WARNING] 引き続きご利用になる場合は下記までご連絡下さい
[2022-07-17 08:42:22,404] [face01lib.Core] [Calc.py] [WARNING] 東海顔認証 担当: 袈裟丸 y.kesamaru@tokai-kaoninsho.com
[2022-07-17 15:45:06,967] [face01lib.video_capture] [video_capture.py] [WARNING] 以下のエラーをシステム管理者へお伝えください
[2022-07-17 15:45:06,968] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-07-17 15:45:06,969] [face01lib.video_capture] [video_capture.py] [WARNING] Traceback (most recent call last):
  File "/home/terms/bin/FACE01/face01lib/video_capture.py", line 222, in frame_generator
    frame  = cv2.cvtColor(img_np, cv2.COLOR_RGBA2BGR)
NameError: name 'cv2' is not defined

[2022-07-17 15:45:06,970] [face01lib.video_capture] [video_capture.py] [ERROR] 通信に異常が発生しました
Traceback (most recent call last):
  File "/home/terms/bin/FACE01/face01lib/video_capture.py", line 222, in frame_generator
    frame  = cv2.cvtColor(img_np, cv2.COLOR_RGBA2BGR)
NameError: name 'cv2' is not defined
[2022-07-17 15:45:06,971] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-07-17 15:45:06,971] [face01lib.video_capture] [video_capture.py] [WARNING] 終了します
[2022-07-17 16:15:59,597] [face01lib.video_capture] [video_capture.py] [WARNING] 以下のエラーをシステム管理者へお伝えください
[2022-07-17 16:15:59,597] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-07-17 16:15:59,598] [face01lib.video_capture] [video_capture.py] [WARNING] Traceback (most recent call last):
  File "/home/terms/bin/FACE01/face01lib/video_capture.py", line 219, in frame_generator
    if response.headers['Content-type'] == 'image/jpeg':
UnboundLocalError: local variable 'response' referenced before assignment

[2022-07-17 16:15:59,598] [face01lib.video_capture] [video_capture.py] [ERROR] 通信に異常が発生しました
Traceback (most recent call last):
  File "/home/terms/bin/FACE01/face01lib/video_capture.py", line 219, in frame_generator
    if response.headers['Content-type'] == 'image/jpeg':
UnboundLocalError: local variable 'response' referenced before assignment
[2022-07-17 16:15:59,599] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-07-17 16:15:59,599] [face01lib.video_capture] [video_capture.py] [WARNING] 終了します
[2022-07-17 16:16:43,156] [face01lib.video_capture] [video_capture.py] [WARNING] 以下のエラーをシステム管理者へお伝えください
[2022-07-17 16:16:43,157] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-07-17 16:16:43,157] [face01lib.video_capture] [video_capture.py] [WARNING] Traceback (most recent call last):
  File "/home/terms/bin/FACE01/face01lib/video_capture.py", line 219, in frame_generator
    if response.headers['Content-type'] == 'image/jpeg':
UnboundLocalError: local variable 'response' referenced before assignment

[2022-07-17 16:16:43,158] [face01lib.video_capture] [video_capture.py] [ERROR] 通信に異常が発生しました
Traceback (most recent call last):
  File "/home/terms/bin/FACE01/face01lib/video_capture.py", line 219, in frame_generator
    if response.headers['Content-type'] == 'image/jpeg':
UnboundLocalError: local variable 'response' referenced before assignment
[2022-07-17 16:16:43,158] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-07-17 16:16:43,158] [face01lib.video_capture] [video_capture.py] [WARNING] 終了します
[2022-07-17 16:17:54,223] [face01lib.video_capture] [video_capture.py] [WARNING] 以下のエラーをシステム管理者へお伝えください
[2022-07-17 16:17:54,223] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-07-17 16:17:54,225] [face01lib.video_capture] [video_capture.py] [WARNING] Traceback (most recent call last):
  File "/home/terms/bin/FACE01/face01lib/video_capture.py", line 219, in frame_generator
    if response.headers['Content-type'] == 'image/jpeg':
UnboundLocalError: local variable 'response' referenced before assignment

[2022-07-17 16:17:54,225] [face01lib.video_capture] [video_capture.py] [ERROR] 通信に異常が発生しました
Traceback (most recent call last):
  File "/home/terms/bin/FACE01/face01lib/video_capture.py", line 219, in frame_generator
    if response.headers['Content-type'] == 'image/jpeg':
UnboundLocalError: local variable 'response' referenced before assignment
[2022-07-17 16:17:54,226] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-07-17 16:17:54,226] [face01lib.video_capture] [video_capture.py] [WARNING] 終了します
[2022-07-17 16:19:02,765] [face01lib.video_capture] [video_capture.py] [WARNING] 以下のエラーをシステム管理者へお伝えください
[2022-07-17 16:19:02,766] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-07-17 16:19:02,767] [face01lib.video_capture] [video_capture.py] [WARNING] Traceback (most recent call last):
  File "/home/terms/bin/FACE01/face01lib/video_capture.py", line 219, in frame_generator
    if response.headers['Content-type'] == 'image/jpeg':
UnboundLocalError: local variable 'response' referenced before assignment

[2022-07-17 16:19:02,767] [face01lib.video_capture] [video_capture.py] [ERROR] 通信に異常が発生しました
Traceback (most recent call last):
  File "/home/terms/bin/FACE01/face01lib/video_capture.py", line 219, in frame_generator
    if response.headers['Content-type'] == 'image/jpeg':
UnboundLocalError: local variable 'response' referenced before assignment
[2022-07-17 16:19:02,768] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-07-17 16:19:02,768] [face01lib.video_capture] [video_capture.py] [WARNING] 終了します
[2022-07-24 18:47:25,949] [face01lib.video_capture] [video_capture.py] [WARNING] USBカメラの受信が出来ません
[2022-07-24 18:47:25,963] [face01lib.video_capture] [video_capture.py] [WARNING] 以下のエラーをシステム管理者へお伝えください
[2022-07-24 18:47:25,963] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-07-24 18:47:25,964] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-07-24 18:47:25,964] [face01lib.video_capture] [video_capture.py] [ERROR] USBカメラとの通信に異常が発生しました
NoneType: None
[2022-07-24 18:47:25,965] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-07-24 18:47:25,965] [face01lib.video_capture] [video_capture.py] [WARNING] 終了します
[2022-07-31 07:29:55,148] [face01lib.video_capture] [video_capture.py] [WARNING] USBカメラの受信が出来ません
[2022-07-31 07:29:55,148] [face01lib.video_capture] [video_capture.py] [WARNING] 以下のエラーをシステム管理者へお伝えください
[2022-07-31 07:29:55,149] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-07-31 07:29:55,150] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-07-31 07:29:55,151] [face01lib.video_capture] [video_capture.py] [ERROR] USBカメラとの通信に異常が発生しました
NoneType: None
[2022-07-31 07:29:55,152] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-07-31 07:29:55,153] [face01lib.video_capture] [video_capture.py] [WARNING] 終了します
[2022-08-01 09:23:09,963] [face01lib.video_capture] [video_capture.py] [WARNING] 受信できません
[2022-08-01 09:23:09,964] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-01 09:23:09,965] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-01 09:23:09,966] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-01 09:23:09,966] [face01lib.video_capture] [video_capture.py] [WARNING] 終了します
[2022-08-01 09:24:07,149] [face01lib.video_capture] [video_capture.py] [WARNING] 受信できません
[2022-08-01 09:24:07,150] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-01 09:24:07,151] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-01 09:24:07,152] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-01 09:24:07,153] [face01lib.video_capture] [video_capture.py] [WARNING] 終了します
[2022-08-01 09:25:01,320] [face01lib.video_capture] [video_capture.py] [WARNING] 受信できません
[2022-08-01 09:25:02,255] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-01 09:25:03,111] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-01 09:25:04,984] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-01 09:25:05,599] [face01lib.video_capture] [video_capture.py] [WARNING] 終了します
[2022-08-01 09:31:43,676] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：-5
[2022-08-01 09:34:19,515] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：-5
[2022-08-01 17:27:53,915] [face01lib.video_capture] [video_capture.py] [WARNING] USBカメラの受信が出来ません
[2022-08-01 17:27:53,915] [face01lib.video_capture] [video_capture.py] [WARNING] 以下のエラーをシステム管理者へお伝えください
[2022-08-01 17:27:53,916] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-01 17:27:53,916] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-01 17:27:53,917] [face01lib.video_capture] [video_capture.py] [ERROR] USBカメラとの通信に異常が発生しました
NoneType: None
[2022-08-01 17:27:53,917] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-01 17:27:53,918] [face01lib.video_capture] [video_capture.py] [WARNING] 終了します
[2022-08-01 17:28:16,881] [face01lib.video_capture] [video_capture.py] [WARNING] USBカメラの受信が出来ません
[2022-08-01 17:28:16,882] [face01lib.video_capture] [video_capture.py] [WARNING] 以下のエラーをシステム管理者へお伝えください
[2022-08-01 17:28:16,882] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-01 17:28:16,882] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-01 17:28:16,883] [face01lib.video_capture] [video_capture.py] [ERROR] USBカメラとの通信に異常が発生しました
NoneType: None
[2022-08-01 17:28:16,884] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-01 17:28:16,884] [face01lib.video_capture] [video_capture.py] [WARNING] 終了します
[2022-08-01 17:29:50,928] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：-5
[2022-08-01 17:34:01,928] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：-5
[2022-08-01 17:48:47,624] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-01 17:52:16,619] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-01 17:52:37,579] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-01 17:54:54,528] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-01 17:55:48,114] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-01 17:56:16,516] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 07:32:04,876] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 07:32:34,804] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 07:33:26,490] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 07:34:02,311] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 07:35:16,449] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 07:36:50,557] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 07:52:01,817] [face01lib.video_capture] [video_capture.py] [WARNING] USBカメラの受信が出来ません
[2022-08-02 07:52:01,817] [face01lib.video_capture] [video_capture.py] [WARNING] 以下のエラーをシステム管理者へお伝えください
[2022-08-02 07:52:01,818] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-02 07:52:01,819] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-02 07:52:01,819] [face01lib.video_capture] [video_capture.py] [ERROR] USBカメラとの通信に異常が発生しました
NoneType: None
[2022-08-02 07:52:01,820] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-02 07:52:01,820] [face01lib.video_capture] [video_capture.py] [WARNING] 終了します
[2022-08-02 07:52:23,379] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 07:55:20,593] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 07:56:22,031] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 07:58:33,356] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 09:07:27,433] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 09:12:08,771] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 09:20:06,134] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 09:21:05,012] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 09:22:03,976] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 09:29:22,266] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 09:30:18,085] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 09:32:39,020] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 09:45:08,880] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 09:49:36,737] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 10:06:31,690] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 10:16:13,696] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 11:25:50,402] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 11:36:17,726] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 11:41:07,784] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 11:41:37,779] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 11:42:32,082] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 11:45:46,385] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 11:47:01,494] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 11:49:26,752] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 11:51:52,784] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 11:54:48,236] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 11:58:13,768] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 12:00:01,378] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 12:02:09,461] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 12:06:53,426] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 12:10:15,336] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-02 12:12:29,343] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-06 16:52:58,301] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-06 16:55:05,753] [face01lib.video_capture] [video_capture.py] [INFO] カメラデバイス番号：0
[2022-08-07 09:42:29,913] [face01lib.video_capture] [FACE01.py] [INFO] カメラデバイス番号：0
[2022-08-07 09:42:51,682] [face01lib.video_capture] [FACE01.py] [INFO] カメラデバイス番号：0
[2022-08-07 09:44:33,285] [face01lib.video_capture] [FACE01.py] [INFO] カメラデバイス番号：0
[2022-08-07 16:38:43,660] [face01lib.video_capture] [FACE01.py] [INFO] カメラデバイス番号：0
[2022-08-07 16:39:19,720] [face01lib.video_capture] [FACE01.py] [INFO] カメラデバイス番号：0
[2022-08-07 16:39:51,502] [face01lib.video_capture] [FACE01.py] [INFO] カメラデバイス番号：0
[2022-08-07 16:40:48,188] [face01lib.video_capture] [FACE01.py] [INFO] カメラデバイス番号：0
[2022-08-07 16:41:25,559] [face01lib.video_capture] [FACE01.py] [INFO] カメラデバイス番号：0
[2022-08-07 17:00:33,806] [face01lib.video_capture] [FACE01.py] [INFO] カメラデバイス番号：0
[2022-08-08 10:59:49,281] [face01lib.video_capture] [FACE01.py] [WARNING] 受信できません
[2022-08-08 10:59:49,282] [face01lib.video_capture] [FACE01.py] [WARNING] --------------------
[2022-08-08 10:59:49,283] [face01lib.video_capture] [FACE01.py] [WARNING] NoneType: None

[2022-08-08 10:59:49,284] [face01lib.video_capture] [FACE01.py] [WARNING] --------------------
[2022-08-08 10:59:49,285] [face01lib.video_capture] [FACE01.py] [WARNING] 終了します
[2022-08-08 11:01:14,861] [face01lib.video_capture] [FACE01.py] [WARNING] 受信できません
[2022-08-08 11:01:14,862] [face01lib.video_capture] [FACE01.py] [WARNING] --------------------
[2022-08-08 11:01:14,862] [face01lib.video_capture] [FACE01.py] [WARNING] NoneType: None

[2022-08-08 11:01:14,862] [face01lib.video_capture] [FACE01.py] [WARNING] --------------------
[2022-08-08 11:01:14,862] [face01lib.video_capture] [FACE01.py] [WARNING] 終了します
[2022-08-08 11:02:14,645] [face01lib.video_capture] [FACE01.py] [WARNING] 受信できません
[2022-08-08 11:02:14,645] [face01lib.video_capture] [FACE01.py] [WARNING] --------------------
[2022-08-08 11:02:14,646] [face01lib.video_capture] [FACE01.py] [WARNING] NoneType: None

[2022-08-08 11:02:14,646] [face01lib.video_capture] [FACE01.py] [WARNING] --------------------
[2022-08-08 11:02:14,646] [face01lib.video_capture] [FACE01.py] [WARNING] 終了します
[2022-08-08 11:06:18,415] [face01lib.video_capture] [video_capture.py] [WARNING] 受信できません
[2022-08-08 11:06:18,416] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 11:06:18,417] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-08 11:06:18,417] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 11:06:18,418] [face01lib.video_capture] [video_capture.py] [WARNING] 終了します
[2022-08-08 11:37:04,184] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-08 11:37:04,185] [face01lib.video_capture] [video_capture.py] [WARNING] REPORTED BY FACE01
[2022-08-08 11:37:04,185] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 11:37:04,186] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-08 11:37:04,186] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 11:41:44,074] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-08 11:41:44,075] [face01lib.video_capture] [video_capture.py] [WARNING] REPORTED BY FACE01
[2022-08-08 11:41:44,075] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 11:41:44,076] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-08 11:41:44,076] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 11:44:24,227] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-08 11:44:24,227] [face01lib.video_capture] [video_capture.py] [WARNING] REPORTED BY FACE01
[2022-08-08 11:44:24,228] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 11:44:24,228] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-08 11:44:24,228] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 11:51:22,770] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-08 11:51:22,770] [face01lib.video_capture] [video_capture.py] [WARNING] REPORTED BY FACE01
[2022-08-08 11:51:22,771] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 11:51:22,772] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-08 11:51:22,772] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 11:57:21,127] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-08 11:57:21,128] [face01lib.video_capture] [video_capture.py] [WARNING] DATA RECEPTION HAS ENDED
[2022-08-08 11:57:21,128] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 11:57:21,129] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-08 11:57:21,129] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 12:01:49,447] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-08 12:01:49,448] [face01lib.video_capture] [video_capture.py] [WARNING] DATA RECEPTION HAS ENDED
[2022-08-08 12:01:49,448] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 12:01:49,449] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-08 12:01:49,450] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 12:05:38,464] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-08 12:05:38,464] [face01lib.video_capture] [video_capture.py] [WARNING] DATA RECEPTION HAS ENDED
[2022-08-08 12:05:38,465] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 12:05:38,465] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-08 12:05:38,466] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 12:08:41,706] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-08 12:08:41,707] [face01lib.video_capture] [video_capture.py] [WARNING] DATA RECEPTION HAS ENDED
[2022-08-08 12:08:41,707] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 12:08:41,708] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-08 12:08:41,709] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 13:11:47,017] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-08 13:11:47,018] [face01lib.video_capture] [video_capture.py] [WARNING] DATA RECEPTION HAS ENDED
[2022-08-08 13:11:47,018] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 13:11:47,019] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-08 13:11:47,019] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 19:38:04,095] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-08 19:38:04,099] [face01lib.video_capture] [video_capture.py] [WARNING] DATA RECEPTION HAS ENDED
[2022-08-08 19:38:04,099] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-08 19:38:04,099] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-08 19:38:04,100] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-09 03:15:31,204] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-09 03:15:31,208] [face01lib.video_capture] [video_capture.py] [WARNING] DATA RECEPTION HAS ENDED
[2022-08-09 03:15:31,208] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-09 03:15:31,209] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-09 03:15:31,209] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-09 03:23:08,690] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-09 03:23:08,690] [face01lib.video_capture] [video_capture.py] [WARNING] DATA RECEPTION HAS ENDED
[2022-08-09 03:23:08,691] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-09 03:23:08,692] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-09 03:23:08,692] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-09 03:25:47,639] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-09 03:25:47,639] [face01lib.video_capture] [video_capture.py] [WARNING] DATA RECEPTION HAS ENDED
[2022-08-09 03:25:47,640] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-09 03:25:47,640] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-09 03:25:47,641] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-09 03:33:30,426] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-09 03:33:30,427] [face01lib.video_capture] [video_capture.py] [WARNING] DATA RECEPTION HAS ENDED
[2022-08-09 03:33:30,427] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-09 03:33:30,428] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-09 03:33:30,428] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-09 03:41:00,994] [face01lib.video_capture] [video_capture.py] [WARNING] ERROR OCURRED
[2022-08-09 03:41:00,995] [face01lib.video_capture] [video_capture.py] [WARNING] DATA RECEPTION HAS ENDED
[2022-08-09 03:41:00,995] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-09 03:41:00,996] [face01lib.video_capture] [video_capture.py] [WARNING] NoneType: None

[2022-08-09 03:41:00,996] [face01lib.video_capture] [video_capture.py] [WARNING] --------------------
[2022-08-14 17:29:50,744] [face01lib.video_capture] [FACE01.py] [WARNING] ERROR OCURRED
[2022-08-14 17:29:50,748] [face01lib.video_capture] [FACE01.py] [WARNING] DATA RECEPTION HAS ENDED
[2022-08-14 17:29:50,748] [face01lib.video_capture] [FACE01.py] [WARNING] --------------------
[2022-08-14 17:29:50,748] [face01lib.video_capture] [FACE01.py] [WARNING] NoneType: None

[2022-08-14 17:29:50,749] [face01lib.video_capture] [FACE01.py] [WARNING] --------------------
[2022-08-19 07:51:07,235] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/return_face_image.py
[2022-08-19 07:51:07,239] [face01lib.video_capture] [video_capture.py] [WARNING] 47
[2022-08-19 07:51:10,357] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/return_face_image.py
[2022-08-19 07:51:10,358] [face01lib.video_capture] [video_capture.py] [WARNING] 48
[2022-08-19 07:51:16,374] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/return_face_image.py
[2022-08-19 07:51:16,374] [face01lib.video_capture] [video_capture.py] [WARNING] 47
[2022-08-19 07:51:19,355] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/return_face_image.py
[2022-08-19 07:51:19,356] [face01lib.video_capture] [video_capture.py] [WARNING] 48
[2022-08-19 07:54:46,339] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/return_face_image.py
[2022-08-19 07:54:46,340] [face01lib.video_capture] [video_capture.py] [WARNING] 47
[2022-08-19 07:55:08,388] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/return_face_image.py
[2022-08-19 07:55:08,389] [face01lib.video_capture] [video_capture.py] [WARNING] 49
[2022-08-19 07:55:39,421] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/return_face_image.py
[2022-08-19 07:55:39,423] [face01lib.video_capture] [video_capture.py] [WARNING] 47
[2022-08-19 07:55:52,776] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/return_face_image.py
[2022-08-19 07:55:52,776] [face01lib.video_capture] [video_capture.py] [WARNING] 49
[2022-08-20 15:34:32,677] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/return_face_image.py
[2022-08-20 15:34:32,681] [face01lib.video_capture] [video_capture.py] [WARNING] 47
[2022-08-20 15:34:35,739] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/return_face_image.py
[2022-08-20 15:34:35,740] [face01lib.video_capture] [video_capture.py] [WARNING] 49
[2022-08-21 15:55:49,566] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:49,568] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:51,628] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:51,628] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:52,045] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:52,046] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:52,288] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:52,288] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:52,677] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:52,678] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:53,111] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:53,111] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:53,482] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:53,483] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:53,848] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:53,849] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:54,264] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:54,264] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:54,665] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:54,665] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:55,034] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:55,034] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:55,429] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:55,430] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:56,044] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:56,046] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:56,439] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:56,440] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:56,851] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:56,852] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:57,080] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:57,081] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:57,281] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:57,281] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:57,468] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:57,469] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:57,681] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:57,682] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:57,890] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:57,891] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:58,091] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:58,092] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:58,299] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:58,300] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:58,572] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:58,573] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:58,893] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:58,894] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:59,111] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:59,112] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:59,457] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:59,457] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:55:59,805] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:55:59,805] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:00,245] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:00,246] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:00,622] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:00,623] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:01,012] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:01,013] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:01,416] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:01,417] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:01,829] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:01,830] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:02,204] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:02,204] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:02,568] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:02,569] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:02,986] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:02,987] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:03,392] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:03,393] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:03,830] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:03,831] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:04,221] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:04,222] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:04,602] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:04,602] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:04,972] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:04,972] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:05,341] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:05,342] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:05,744] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:05,745] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:06,160] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:06,161] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:06,571] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:06,572] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:06,978] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:06,979] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:07,404] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:07,404] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:07,795] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:07,795] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:08,172] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:08,172] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:08,581] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:08,582] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:09,017] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:09,018] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:09,420] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:09,421] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:09,823] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:09,824] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:10,255] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:10,255] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:10,658] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:10,658] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:11,030] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:11,031] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:11,411] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:11,412] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:11,824] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:11,825] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:12,214] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:12,214] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:12,618] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:12,619] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:13,042] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:13,043] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:13,455] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:13,456] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:13,838] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:13,839] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:14,285] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:14,285] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:14,717] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:14,718] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:15,113] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:15,114] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:15,536] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:15,537] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:15,958] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:15,959] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:16,386] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:16,386] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:16,770] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:16,770] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:17,138] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:17,138] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:17,546] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:17,547] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:17,929] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:17,930] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:18,330] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:18,331] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:18,750] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:18,751] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:19,197] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:19,198] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:19,626] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:19,626] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:20,071] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:20,072] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:20,484] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:20,484] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:20,879] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:20,880] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:21,309] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:21,310] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:21,744] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:21,744] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:22,158] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:22,159] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:22,551] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:22,552] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:23,010] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:23,010] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:23,448] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:23,448] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:23,914] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:23,915] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:24,326] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:24,327] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:24,721] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:24,722] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:25,137] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:25,137] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:25,492] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:25,493] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:25,924] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:25,924] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:26,170] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:26,171] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:26,549] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:26,549] [face01lib.Core] [Core.py] [WARNING] 460
[2022-08-21 15:56:26,653] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:26,654] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:27,019] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:27,020] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:27,374] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:27,375] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:27,715] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:27,716] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:27,909] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:27,910] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:28,141] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:28,142] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:28,350] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:28,350] [face01lib.Core] [Core.py] [WARNING] 460
[2022-08-21 15:56:28,451] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:28,451] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:28,646] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:28,647] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:28,840] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:28,841] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:29,073] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:29,075] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:29,288] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:29,289] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:29,536] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:29,538] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:29,780] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:29,781] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:29,966] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:29,967] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:30,145] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:30,146] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:30,343] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:30,343] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 15:56:30,578] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 15:56:30,579] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:09,867] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 2
[2022-08-21 16:06:09,868] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:09,869] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:11,877] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-21 16:06:11,878] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:11,878] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:12,332] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 2
[2022-08-21 16:06:12,332] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:12,333] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:12,538] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-21 16:06:12,539] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:12,539] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:12,946] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-21 16:06:12,946] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:12,947] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:13,370] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-21 16:06:13,371] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:13,371] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:13,777] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-21 16:06:13,778] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:13,778] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:14,174] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-21 16:06:14,174] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:14,175] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:14,568] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-21 16:06:14,569] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:14,570] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:14,970] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-21 16:06:14,971] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:14,971] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:15,352] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-21 16:06:15,353] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:15,354] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:15,769] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 4
[2022-08-21 16:06:15,769] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:15,770] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:16,396] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-21 16:06:16,396] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:16,396] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:16,778] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-21 16:06:16,778] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:16,779] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:17,215] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 2
[2022-08-21 16:06:17,216] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:17,217] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:17,458] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 2
[2022-08-21 16:06:17,458] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:17,459] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:17,667] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 2
[2022-08-21 16:06:17,668] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:17,669] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:17,876] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 2
[2022-08-21 16:06:17,877] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:17,878] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:18,101] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 2
[2022-08-21 16:06:18,102] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:18,103] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-21 16:06:18,348] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 2
[2022-08-21 16:06:18,349] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-21 16:06:18,349] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-22 17:22:52,646] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 2
[2022-08-22 17:22:52,648] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-22 17:22:52,649] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-22 17:22:58,192] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-22 17:22:58,193] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-22 17:22:58,193] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-22 17:22:58,707] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 2
[2022-08-22 17:22:58,708] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-22 17:22:58,709] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-22 17:22:58,995] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-22 17:22:58,996] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-22 17:22:58,998] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-22 17:22:59,454] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-22 17:22:59,456] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-22 17:22:59,457] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-22 17:22:59,968] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-22 17:22:59,968] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-22 17:22:59,969] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-22 17:23:00,449] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-22 17:23:00,450] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-22 17:23:00,451] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-22 17:23:00,902] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-22 17:23:00,903] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-22 17:23:00,905] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-22 17:23:01,380] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-22 17:23:01,381] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-22 17:23:01,382] [face01lib.Core] [Core.py] [WARNING] 546
[2022-08-25 20:35:02,030] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 2
[2022-08-25 20:35:02,032] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/lib/python3.8/site-packages/memory_profiler.py
[2022-08-25 20:35:02,034] [face01lib.Core] [Core.py] [WARNING] 759
[2022-08-25 20:35:04,376] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-25 20:35:04,378] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/lib/python3.8/site-packages/memory_profiler.py
[2022-08-25 20:35:04,380] [face01lib.Core] [Core.py] [WARNING] 759
[2022-08-25 20:35:05,210] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 2
[2022-08-25 20:35:05,212] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/lib/python3.8/site-packages/memory_profiler.py
[2022-08-25 20:35:05,214] [face01lib.Core] [Core.py] [WARNING] 759
[2022-08-25 20:35:05,601] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-25 20:35:05,602] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/lib/python3.8/site-packages/memory_profiler.py
[2022-08-25 20:35:05,604] [face01lib.Core] [Core.py] [WARNING] 759
[2022-08-25 20:35:06,298] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-25 20:35:06,300] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/lib/python3.8/site-packages/memory_profiler.py
[2022-08-25 20:35:06,302] [face01lib.Core] [Core.py] [WARNING] 759
[2022-08-25 20:35:07,028] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-25 20:35:07,031] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/lib/python3.8/site-packages/memory_profiler.py
[2022-08-25 20:35:07,033] [face01lib.Core] [Core.py] [WARNING] 759
[2022-08-25 20:35:07,775] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-25 20:35:07,776] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/lib/python3.8/site-packages/memory_profiler.py
[2022-08-25 20:35:07,778] [face01lib.Core] [Core.py] [WARNING] 759
[2022-08-25 20:35:08,464] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-25 20:35:08,466] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/lib/python3.8/site-packages/memory_profiler.py
[2022-08-25 20:35:08,468] [face01lib.Core] [Core.py] [WARNING] 759
[2022-08-25 20:35:09,122] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-25 20:35:09,124] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/lib/python3.8/site-packages/memory_profiler.py
[2022-08-25 20:35:09,125] [face01lib.Core] [Core.py] [WARNING] 759
[2022-08-25 20:35:09,830] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-25 20:35:09,833] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/lib/python3.8/site-packages/memory_profiler.py
[2022-08-25 20:35:09,835] [face01lib.Core] [Core.py] [WARNING] 759
[2022-08-25 20:35:10,588] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-25 20:35:10,589] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/lib/python3.8/site-packages/memory_profiler.py
[2022-08-25 20:35:10,592] [face01lib.Core] [Core.py] [WARNING] 759
[2022-08-25 20:35:11,383] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 4
[2022-08-25 20:35:11,386] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/lib/python3.8/site-packages/memory_profiler.py
[2022-08-25 20:35:11,388] [face01lib.Core] [Core.py] [WARNING] 759
[2022-08-25 20:35:12,459] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-25 20:35:12,460] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/lib/python3.8/site-packages/memory_profiler.py
[2022-08-25 20:35:12,463] [face01lib.Core] [Core.py] [WARNING] 759
[2022-08-25 20:42:48,859] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 2
[2022-08-25 20:42:48,860] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-25 20:42:48,862] [face01lib.Core] [Core.py] [WARNING] 564
[2022-08-25 20:42:51,056] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-25 20:42:51,059] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-25 20:42:51,061] [face01lib.Core] [Core.py] [WARNING] 564
[2022-08-25 20:42:51,701] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 2
[2022-08-25 20:42:51,704] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-25 20:42:51,707] [face01lib.Core] [Core.py] [WARNING] 564
[2022-08-25 20:42:52,074] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-25 20:42:52,075] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-25 20:42:52,076] [face01lib.Core] [Core.py] [WARNING] 564
[2022-08-25 20:42:52,704] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-25 20:42:52,706] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-25 20:42:52,710] [face01lib.Core] [Core.py] [WARNING] 564
[2022-08-25 20:42:53,287] [face01lib.Core] [Core.py] [WARNING] frame_datas_array size: 3
[2022-08-25 20:42:53,288] [face01lib.Core] [Core.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-25 20:42:53,289] [face01lib.Core] [Core.py] [WARNING] 564
[2022-08-28 11:56:04,254] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-28 11:56:04,256] [face01lib.video_capture] [video_capture.py] [WARNING] 100
[2022-08-28 12:03:43,277] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-28 12:03:43,278] [face01lib.video_capture] [video_capture.py] [WARNING] 100
[2022-08-28 12:05:00,222] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-28 12:05:00,223] [face01lib.video_capture] [video_capture.py] [WARNING] 100
[2022-08-28 12:07:39,358] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-28 12:07:39,359] [face01lib.video_capture] [video_capture.py] [WARNING] 100
[2022-08-28 12:10:45,248] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-28 12:10:45,249] [face01lib.video_capture] [video_capture.py] [WARNING] 100
[2022-08-28 12:13:21,575] [face01lib.video_capture] [video_capture.py] [WARNING] /home/terms/bin/FACE01/face01lib/Core.py
[2022-08-28 12:13:21,576] [face01lib.video_capture] [video_capture.py] [WARNING] 100
